### ISSUE TITLE
Tutorials broken

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#514] opened 2023-10-10 09:23 UTC
When trying to test tutorials (next recompiled this morning), I just get the first `<step>` displayed and read aloud.
I also instantly see "Tutorial finished.". It seems the tutorial is finished early after executing the first `<step>`.

It also happens with the autogenerated tutorials for the checklist, but _not_ for tutorials on the C177p.

**Comment by wlbragg** [comment] 2023-10-10 15:12
What are the differences between a working c172p and a non-working c182 tutorial?

Have you compared similar tutorial?

**Comment by hbeni** [comment] 2023-10-10 20:30
I tried to see differences, but especially the winter flying tutorial is so dead simple… its just messages and waits…

See: https://github.com/HHS81/c182s/blob/master/Tutorials/winterFlying.xml

**Comment by wlbragg** [comment] 2023-10-10 22:46
I just tried one and it is broke from a rebuild of next as of a few days ago. Are any of these tutorials new?

**Comment by wlbragg** [comment] 2023-10-10 22:59
Hum, it's also broke in 2020.3 using the current c182s.

**Comment by wlbragg** [comment] 2023-10-10 23:03
OK, now this is really strange. Your winter tutorial works just fine in the c172p, so this has to be something in the c182 causing a failure.

**Comment by wlbragg** [comment] 2023-10-10 23:17
I've eliminated either a different checklist or tutorial being the cause of this by isolation only the winter tutorial  Everything else was removed to make sure there wasn't some weird formatting error in one of the other tutorials or checklists.
I am seeing Tutorial Finished, and then the first step and then nothing else. I don't think we should see Tutorial Finished before the first step verbiage. That makes no sense.

**Comment by hbeni** [comment] 2023-10-11 05:27
Thank you for investigating.

I really wonder what can cause this

**Comment by wlbragg** [comment] 2023-10-12 01:27
@hbeni 
I think I found the issue
Comment out line
925 in Nasal/c182s.nas
~~~
setlistener("/engines/engine/crashed", func(n) {setprop("/sim/crashed", n.getBoolValue());});
~~~

**Comment by hbeni** [comment] 2023-10-12 06:59
Thank you for finding this!

But why on earth does a listener break tutorials?

**Comment by wlbragg** [comment] 2023-10-12 20:09
I have no idea. I looked at it from every angle and can't answer why. We have a few listeners in c172p.nas with no flags and they are not a problem. I tried moving it outside of the "FDM loaded" listener, that didn't change anything. The only thing I can think of is that the /engines/engine/crashed property isn't available when the listener is first initialized and causing some kind of corruption. But I don't remember exactly what the flags do or what the default is in regards to execution, as in when it is executed for the first time.

**Comment by TheFGFSEagle** [comment] 2023-10-12 23:46
From the wiki for `setlistener`:
> * init
>     If set to 1 (true), the listener will additionally be triggered when it is created. This argument is optional and defaults to 0 (false).
> * type
>     Integer specifying the listener's behavior. 0 means that the listener will only trigger when the property is changed. 1 means that the trigger will always be triggered when the property is written to. 2 will mean that the listener will be triggered even if child properties are modified. This argument is optional and defaults to 1.

But I don't see how the listener triggering only when the property is changed vs. triggering whenver the propery is written to could make any difference on tutorials … 

@wlbragg do try setting the second flag to 1 for that listener on the 172

**Comment by TheFGFSEagle** [comment] 2023-10-12 23:48
and if you change that line to
```nasal
setlistener("/engines/engine/crashed", func(n) {setprop("/sim/crashed", 0);}, 0, 0);

**Comment by wlbragg** [comment] 2023-10-13 02:39
>@wlbragg do try setting the second flag to 1 for that listener on the 172

Which one and why? We have  couple I think that use whatever the default is.

**Comment by hbeni** [comment] 2023-10-13 07:19
Changing that line did not help at my end. Still broken...

But reverting a878fcb9ac54aff75aa1c6b5c458758f4b3c5675 did help indeed.... So it has definitely to do with that commit.

**Closed** 2023-10-13 07:39 UTC
Labels: bug, tutorials

**Comment by hbeni** [comment] 2023-10-13 07:45
Found it.
Wayne, your approach was indeed right, however it triggered something differently here.
But the problem was definitely the listener in `c182s.nas`.

I removed that and refactored the ELT crash listener to the `engines/engine/crashed` prop.
This works.
I assume, in `c182s.nas` it's just too early to initialize this, or the chaining of the listeners/aliasing was causing trouble.
