### ISSUE TITLE
Issue with towbar FG 2020.4

### ISSUE THREAD

**Issue by jakkos98** [HHS81/c182s#560] opened 2024-01-26 00:07 UTC
After selecting towbar clickspot for nose wheel chock is no longer working. Both disabling of towbar and puting wheel chock can be done later only via menu dialogs.

Best regards 
Jakub Kosakowski

**Comment by hbeni** [comment] 2024-01-26 06:38
Could not reproduce here, working in all combinationsand with many repetitions.

What exact plane version did you use?
- The latest release from FGAddon,
- or the github one here?

**Comment by hbeni** [comment] 2024-01-26 09:28
Or am I misunderstanding the issue?
Since the towbar addition, the nose wheel clickspot was transferred to a menu, because there is more than one option now.
This will also happen to the main wheels some time ahead, when wear and tear is going to be modelled.

**Comment by TheFGFSEagle** [comment] 2024-01-26 13:47
Will check that out as well when I test the prop shadows.

**Comment by hbeni** [comment] 2024-01-26 15:30
Thanks Eagle!
I could not reproduce it, and maybe it is just a misunderstanding on my side; I think we need feedback from @jakkos98

**Comment by jakkos98** [comment] 2024-01-26 22:55
Looks like issue was only on FG nightly from 24.01.2024 (or earlier) and on FG nightly from 25.01.2024 everything is working as it should. (C182S from FGAddon)

**Comment by hbeni** [comment] 2024-01-27 09:22
Thx for the Feedback!

**Closed by hbeni** 2024-01-27 09:22 UTC
Labels: bug, wontfix

**Comment by TheFGFSEagle** [comment] 2024-01-28 16:21
I tested with a relatively old FG build (perhaps 1-2 months old), and  the clickspot at the nose gear wasn't working at all.
