### ISSUE TITLE
Implement Multiplayer compatibility

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#178] opened 2017-10-28 17:13 UTC
Make aircraft showing correctly in multiplayer with all liverys, esp. custom callsign one

- [x] xpdr has been merged:
  - Transponder does work in OpenRadar and ATC-Pie
  - Transponder IDENT does work too
- [x] Pending:
  - [x] show correct model
  - [x] Flight Control Surfaces
  - [x] different liveries
  - [x] registration in the custom livery (corebug -> see https://github.com/c172p-team/c172p/issues/1339)
  - [x] lights
    - [x] landing lights
    - [x] taxi lights
    - [x] beacon
    - [x] nav lights
  - [x] Cowl flaps

**Comment by hbeni** [comment] 2017-10-28 19:31
Just tested: base livery work already. Missing seems things like opening doors, landing lights, custom registration number showing, etc

**Comment by HHS81** [comment] 2017-11-26 18:47
Multiplay seems quite to need a lot of ressources. I do know a lot users who are complaining about other mp-aircraft, which slows down or even freezes the sim when they appear.

I don't think that the other user need to see the doors opening. What is important are lights, liveries and registration and flight control surfaces (incl. cowl flap).
All other this is not really needed.

**Comment by hbeni** [comment] 2018-11-12 11:19
Also, transponder working correctly with atc clients (ie openradar) should be verified. While beeing at this, we might make the factory vfr code setting accessible via the aircraft dialog.

**Comment by HHS81** [comment] 2018-11-13 17:58
@hbeni 
I can`t tell for sure, but I think the EC 135 P2s transponder supports the transmitting if the transponder code. So we might loook how it is done to complete the implementation.

**Comment by hbeni** [comment] 2018-11-17 13:50
I started something in the [`xpdrMP`](https://github.com/HHS81/c182s/tree/xpdrMP) branch.
ID Button is already working and the internals seem good - however no id is transmitted. I asked on the mailing list about this.

**Comment by hbeni** [comment] 2018-12-07 13:41
https://github.com/HHS81/c182s/tree/xpdrMP is now working in ATCPie :)
We can fly and interact correctly with ATCs now.

till open is the higlight of the Ident button, when the id is actively sendet.

**Comment by hbeni** [comment] 2020-10-21 05:56
To brush this up a little:
- [x] xpdr has been merged:
  - Transponder does work in OpenRadar and ATC-Pie
  - Transponder IDENT does work too
- [ ] Testing pending:
  - [ ] lights should be verified, but i expect them to work
  - [ ] different liveries
  - [ ] registration in the custom livery
  - [ ] Cowl flaps
  - [ ] Flight Control Surfaces

**Comment by Zaretto** [comment] 2020-10-21 14:45
The fallback model will be used when other MP pilots do not have the c182s installed *or* when the LOD settings require that a low detail model is used. This is normal and there isn't any other way to do this.

Control surfaces, Liveries, Registrations, Lights, Cowl Flaps will usually require the detailed model (i.e to have the c182s) and setting properties that are transmitted over MP as defined here http://wiki.flightgear.org/Multiplayer_protocol#Properties_transmitted_over_MP. 

If you are using a property to animate a surface that isn't in the list of properties transmitted over MP then you will need to use a generic property.

I usually do this like this

in the -set.xml

    <sim>
        <multiplay>
            <generic>
                <float n="8" alias="/engines/engine[0]/augmentation-burner" />
                <float n="9" alias="/engines/engine[1]/augmentation-burner" />
                <float n="10" alias="/fdm/jsbsim/propulsion/engine[0]/alt/nozzle-pos-norm" />
                <float n="11" alias="/fdm/jsbsim/propulsion/engine[1]/alt/nozzle-pos-norm" />
                <float n="12" alias="/surface-positions/l-ramp1-position-deg" />
                <float n="13" alias="/surface-positions/r-ramp1-position-deg" />
                <float n="14" alias="/fdm/jsbsim/systems/electrics/ac-essential-bus1" />
                <float n="15" alias="/fdm/jsbsim/systems/electrics/ac-left-main-bus" />
                <float n="16" alias="/engines/engine[0]/afterburner" />
                <float n="17" alias="/engines/engine[1]/afterburner" />
            </generic>
        </multiplay>
    </sim>

in the model.xml

    <animation>
        <type>rotate</type>
        <object-name>IntakeRampL0</object-name>
        
        <object-name>IntakeRampL2</object-name>
        <object-name>IntakeRampL3</object-name>
        <property>sim/multiplay/generic/float[12]</property>
        <center>
            <x-m>-2.06031</x-m>
            <y-m>-0.87825</y-m>
            <z-m>-0.16711</z-m>
        </center>
        <axis>
            <x>0</x>
            <y>-1</y>
            <z>0</z>
        </axis>
    </animation>

Remember that you must never have a leading / on the properties in your model xml files; sim/multiplay/generic/float[12] is good but /sim/multiplay/generic/float[12] is wrong and will point to the remote pilots generic/float[12] and not your model because in MP your model's property tree has its root at  ai/models/multiplayer[#]

Also it is only the main 3d model that is loaded (e.g. c182s/Models/c182s.xml) - no Nasal, no systems, no aero, the only Nasal that is loaded is in the main model <load> section - and model Nasal needs to be kept to a minimum - often just the livery update.

**Comment by hbeni** [comment] 2020-10-21 18:03
Thank you for elaborating. Very good points!

My problem however is, that it looks like the real model doesn’t get loaded - only the fallback one will.
I’m clueless why this happens.

I also made a post at the fgfs forums with more details (esp. what i tested/tried) in the hope of getting advice: https://forum.flightgear.org/viewtopic.php?f=4&t=38161

**Comment by Zaretto** [comment] 2020-10-21 20:20
I've just tested this and the full detail model is loaded perfectly. 

There were some problems with paths and an error in the JSBSim file that I've also fixed whilst I was testing.

The only thing that strikes me as odd is that the aircraft is very black on the remote MP instance; possibly something related to a shader being used on the livery.

**Comment by HHS81** [comment] 2020-10-21 20:22
> 
> 
> I've just tested this and the full detail model is loaded perfectly.
> 
> There were some problems with paths and an error in the JSBSim file that I've also fixed whilst I was testing.
> 
> The only thing that strikes me as odd is that the aircraft is very black on the remote MP instance; possibly something related to a shader being used on the livery.

That´s because the new paths doesn`t work with the shader. I experienced this long ago

**Comment by hbeni** [comment] 2020-10-21 20:24
Richard, how exactly did you test, so i can do the same?

**Comment by hbeni** [comment] 2020-10-22 05:45
@Zaretto Richard, how exactly did you test, so i can do the same?
- what fgfs version are you using?
- how did you install the aircraft?
- how did you start fgfs?

**Comment by hbeni** [comment] 2020-10-22 10:27
Hmmm!!!
I disconnected and reconnected several times and then it reliably "worked".
When starting offline, wait a few seconds to settle, then connecting, it works too.
![grafik](https://user-images.githubusercontent.com/13608602/96859205-84f58c00-1461-11eb-8752-610c68713b51.png)

Maybe it's just a model load race condition when starting with enabled multiplayer?

As soon as damage occurs, the model reverts to the fallback one, tough (but that is surely another problem).

**Comment by hbeni** [comment] 2020-10-22 10:34
Some strange effect when the fallback is loaded:
![grafik](https://user-images.githubusercontent.com/13608602/96860337-ec600b80-1462-11eb-9488-c5b1496a7d2d.png)


But its visible from insde:
![grafik](https://user-images.githubusercontent.com/13608602/96860277-d94d3b80-1462-11eb-95d5-317a9f0adf7e.png)

**Comment by Zaretto** [comment] 2020-10-22 17:27
I'm testing using 2020.4 (next).

Please remember that the fallback model will load very quickly and the high detail model can take a minute or more to load and whilst the high detail model is loaded the low detail model will be shown. AI model loading happens on a background thread which means that FG doesn't pause (except for the mipmap generation when using textures that don't have a mipmap).

Use View -> Adjust LOD -> AI/MP aircraft the first dropdown you can choose "Specify Ranges" to "Low Detail only" or "High detail only" to control how the fallback model is used.

c182s started with

fgfs.exe "--aircraft=c182s" "--airport=FHAW"        "--fg-root=e:\temp\fgdata" "--fg-scenery=i:/flightgear/scenery" "--fg-scenery=i:/flightgear/custom_scenery" "--terrasync-dir=i:\flightgear\terrasync" "--fg-aircraft=i:/dev/flightgear-models/flightgear/aircraft" "--fg-aircraft=i:/flightgear/oprf_assets" "--fg-aircraft=i:/flightgear/aircraft" "--fg-aircraft=E:/Users/richard/dev/fguk/Aircraft" "--fg-aircraft=i:/fgaddon/trunk/aircraft" "--callsign=Richard" "--multiplay=out,10,mpserver01.flightgear.org,5000" "--multiplay=in,10,,5002" "--httpd=8080" "--prop:/sim/rendering/vsync-enable=false" "--prop:/sim/frame-rate-throttle-hz=30" "--prop:/sim/startup/terminal-ansi-colors=0" "--bpp=32" "--texture-filtering=32" "--prop:/sim/rendering/multi-sample-buffers=1" "--prop:/sim/rendering/multi-samples=4" "--log-level=alert" "--prop:/sim/rendering/osg-notify-level=FATAL" "--prop:/sim/rendering/max-paged-lod=2000" "--texture-cache-dir=i:/flightgear/texturecache"

Using the UFO as my second aircraft; 

fgfs.exe "--aircraft=ufo" "--airport=FHAW"      "--fg-scenery=i:/flightgear/scenery" "--terrasync-dir=i:\flightgear\terrasync"  "--fg-root=e:\temp\fgdata" --fg-aircraft=i:/dev/flightgear-models/flightgear/aircraft  --fg-aircraft=i:/flightgear/aircraft  --fg-aircraft=i:/fgaddon/trunk/aircraft  "--bpp=32" "--disable-terrasync" "--callsign=John" "--multiplay=out,30,mpserver01.flightgear.org,5000" "--multiplay=in,30,,5006" "--log-level=warn"  "--httpd=8080" "--prop:/sim/rendering/on-screen-statistics=1" "--prop:/sim/rendering/vsync-enable=false" "--prop:/sim/frame-rate-throttle-hz=30" "--prop:/sim/startup/terminal-ansi-colors=0"   --bpp=32  --texture-filtering=8   --prop:/sim/rendering/multi-sample-buffers=1   --prop:/sim/rendering/multi-samples=4  "--texture-cache-dir=i:/flightgear/texturecache"

![image](https://user-images.githubusercontent.com/2045654/96902668-192d1680-1495-11eb-8ded-a74a9b95fa12.png)

Using local loopback to test isn't really the best MP test because you are testing from within the same model; local loopback is good for getting the animations working properly.

There is something weird with the interior model usage; testing the F-15 my interior model was hidden in low detail so I added to my pull request to include some minor changes that fix the interior model appearing in low detail. I don't know why it is necessary to change the model name to interior-model-c182s - possibly a name class; but it now works (for me)

**Comment by HHS81** [comment] 2020-10-22 17:49
The black aircraft is due to the now used path- the effects doesnt work with that.

**Comment by hbeni** [comment] 2020-10-22 20:02
How can that be fixed?

**Comment by Zaretto** [comment] 2020-10-23 10:52
The black remote aircraft was caused by the uber shader using properties that weren't available over MP and therefore defaulted 0.

Fixed in 8ca75f2e1c95952e5fb5b4a16ebf1edcff8b59ff

**Comment by hbeni** [comment] 2020-11-05 20:29
I made a new (local yet) branch, basing on Richards pull request.

There i got everything to work, the only missing bit is the custom registration.
For some weird reason i cannot see it - the needed properties are all there and referenced properly.
Could it be that just the immat.ac model is not loaded at the multiplayer instance?

@wlbragg @gilbertohasnofb  That may be a bug with the system as a whole, because the C172p has the same problem here...

**Comment by wlbragg** [comment] 2020-11-05 21:09
I don't remember what is up with that. I'll take a look at the c172p in multiplayer here in the next couple days and see if I can duplicate and figure out what;s going on.

**Comment by hbeni** [comment] 2020-11-12 13:28
> I don't remember what is up with that. I'll take a look at the c172p in multiplayer here in the next couple days and see if I can duplicate and figure out what;s going on.

Hi, already found something?
For what i've found, the needed properties are transmitted to the remote client and are available there... so it surely must be something related to the model itself?

**Comment by hbeni** [comment] 2020-11-17 10:28
@wlbragg Hello, i digged into the MP immatriculation issue a little further.
It looks like the model _is_ shown, just the text translation is not working properly somehow.
For the most part the text is not readable, but in one occasion i did find some strange black pixels by accident.

So i did go ahead and offset the registration 1m to the top, so it's more obvious.
And indeed, there are some strange black pixels. It looks like the text is horribly distorted, or the texture not mapped properly, but only in the multiplayer instance - which is strange, because the calculated text translate offsets (`sim/model/c182s/regnum[1-5]`) are correct in both instances!

See the screenshot for comparison (left my local window, right ORCAM instance; both connected via local network multiplayer):
![Screenshot_20201117_111355](https://user-images.githubusercontent.com/13608602/99377698-ce04f880-28c6-11eb-8fdc-bd27af268878.png)

**Comment by Zaretto** [comment] 2020-11-17 12:44
It has previously been reported that textranslate doesn't work properly on MP models - which is probably a bug in the core somehwere.

**Comment by hbeni** [comment] 2020-11-17 14:03
Ah, good to know - do you know the place of that reporting?
And is there a solution?

**Comment by wlbragg** [comment] 2020-11-18 11:29
Ah, thanks!

**Comment by hbeni** [comment] 2020-11-20 13:13
I converted the text-translate registration to canvas. This works nicely, even over multiplayer (at least, when i finally found out how simple that was :smile: )

The plane in the middle is a C182T, the other ones are of the S-Variant:
![grafik](https://user-images.githubusercontent.com/13608602/99803915-81295800-2b3a-11eb-810f-b8827fac8ed4.png)

**Closed** 2020-12-05 11:27 UTC
Labels: animations (XML), low priority, multiplayer
