### ISSUE TITLE
Add a flashlight and radiance effect

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#248] opened 2018-02-05 05:24 UTC
Port the ALS flashlight

**Comment by hbeni** [comment] 2018-02-09 22:39
ok, i give up on this. I cant get to grips with that effects stuff.

**Comment by wlbragg** [comment] 2018-02-10 08:39
Would you like me to work on this and get it started? The amount of interior model objects that need to be Inc!used in the effect definition can be considerable.

**Comment by hbeni** [comment] 2018-02-10 12:30
I can't solve this; if you would want to have a try on this? That would be nice!
Currently we have a problem if its night and the electrical system gets down... :)

**Comment by wlbragg** [comment] 2018-02-10 17:01
OK, easy part is done. Look at the two pictures, your layout made it easy to add the flashlight effect to the majority of the interior. The gauges are the difficult part. The historical way of doing gauges makes the ALS rendering framework implementation difficult at best. Every dial/gauge xml file has to be gone through and have the effect applied to every object you what the flashlight effect on.

![](http://i.imgur.com/wbxQTd2.png)

![fgfs-screen-009](https://user-images.githubusercontent.com/11069680/36064516-b42ce2b6-0e51-11e8-9db0-b2f716989c9f.png)

**Comment by wlbragg** [comment] 2018-02-10 17:04
Before I forget, I think the red light flashlight should be the default and the white light should be the alternate choice. In other words, first click turns on the red, second click turns on the white. It is white then red in the c172p. Your wishes?

**Comment by wlbragg** [comment] 2018-02-10 17:39
Another question, do you folks plan on doing interior-radiance? That is the glow on all the interior surfaces caused by the illumination of the all the panel lighting. It's implemented on the c172p. The reason I ask is that would have an impact on the name used for the flashlight on all these gauge xml files. Right now the effect would be called c182s_flashlight. but if you plan to add the interior-radiance, the flashlight functionality is added into that effect file which would be something like c182s_interior-radiance. Now I know that doesn't sound like a big deal, except I did the very same thing on the c172p. I did the flashlight effect on all the gauge xml files only to have to go back in a few weeks later and rename them all. It just a hassle and a step we can avoid if your planning on do interior radiance in the future. If you are, then I would just start out by naming the flashlight effect on all the dials and gauges as c182s_interior-radiance right out of the starting gate.

**Comment by wlbragg** [comment] 2018-02-10 17:51
Not only that but I can go ahead and setup the supporting code for the interior radiance effect now. Then when ready to implement it all we have to do is add the ALS light manager portion (c172p/Systems/als-lights.xml lines 321-424) customized for the c182s.
Thoughts?

**Comment by hbeni** [comment] 2018-02-10 17:56
I think @HHS81 should decide on all this.

**Comment by wlbragg** [comment] 2018-02-10 18:38
@hbeni if you have time while were waiting for @HHS81 to answer, I just pushed the example of how to add the effect to the gauges. I added the effect to the ASI gauge. You can start adding the effect to more gauges if you want. I have to get back to some of my other projects.

**Comment by HHS81** [comment] 2018-02-11 10:02
@wlbragg 
Wow, thanks a bunch! 👍 

I'm not a fan of this radiance effect, somehow it doesn't look right to me. I can very good live without it.

**Comment by hbeni** [comment] 2018-02-11 12:29
When checing out the branch, i get a mass of errors (see below).
Besides that all seems to be working.
The magneto switch socket and key should be added to the effect, as well as the knobs of the Artifical Horizont, Altimeter and NAV1/NAV2 gauges. All else is flashed :)

Very cool!!!

`Splash screen progress binding-subsystems

Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"

Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"

Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"

Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"

Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"

Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"

can't find "../../Models/Effects/c182sreflect-uber.eff"

can't find base effect ../../Models/Effects/c182sreflect-uber

can't find "../../Models/Effects/c182sreflect-uber.eff"

can't find base effect ../../Models/Effects/c182sreflect-uber

can't find "../../Models/Effects/c182sreflect-uber.eff"

can't find base effect ../../Models/Effects/c182sre [...]`

**Comment by hbeni** [comment] 2018-02-11 13:08
Ok, i added them, now it looks all consistent!
Very nice!

The errors above are still here unfortunately (i also  lack the knowledge to fix this - @wlbragg what is causing this?).

**Comment by wlbragg** [comment] 2018-02-11 16:32
I never even looked at my log, I'm getting them too. I did notice one thing on my branch and that was I accidentally pushed a change I have locally. I need relative paths because of all my different aircraft folder structure naming conventions. So I had made a change to some of the effect paths otherwise I got a black aircraft. It's probably something to do with that. Let me put it back to what your original version has and see if that corrects it.

**Comment by wlbragg** [comment] 2018-02-11 17:19
I got to admit, I'm a bit confused here.
I just did a fresh pull of master from here and I get the following
~~~
Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"
Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"
Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"
Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"
Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"
Cannot find image file "Aircraft/c182s/Models/Effects/interior/white.png"
Could not find at least one of the following objects for axis animation: knob-inner-axis
Could not find at least one of the following objects for axis animation: Hdg-Knob-axis
Could not find at least one of the following objects for axis animation: OBS-Knob-axis
Could not find at least one of the following objects for axis animation: click-R-axis
Could not find at least one of the following objects for axis animation: click-R-axis
PNG lib warning : Interlace handling should be turned on when using png_read_image

PNG lib warning : Interlace handling should be turned on when using png_read_image

PNG lib warning : Interlace handling should be turned on when using png_read_image

Could not find at least one of the following objects for axis animation: key-axis
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
can't find "../../Models/Effects/c182sreflect-uber.eff"
can't find base effect ../../Models/Effects/c182sreflect-uber
~~~
So I don't think this is anything I introduced?

**Comment by HHS81** [comment] 2018-02-11 17:40
@wlbragg 
` <inherits-from>../../Models/Effects/c182sreflect-uber</inherits-from>`

**../../Model/...** is one reason for....

I have to sort out the  white.png yet

**Comment by HHS81** [comment] 2018-02-11 17:46
Oh, because there is no white.png - the reason is c182s_flashlight.eff. it doesn't use the cubemaps, instead it links to white.png, which doesn't exists.

**Comment by HHS81** [comment] 2018-02-11 17:47
The same for c182s_interior_radiance.eff

**Comment by wlbragg** [comment] 2018-02-11 17:51
@HHS81 This doesn't make sense because, I am getting my list of errors on your "master" pull of this aircraft. Not only that but on my branch I added white.png to the Models/Effects directory which should not cause any error.

**Comment by HHS81** [comment] 2018-02-11 17:54
@wlbragg I have just fixed those file and pushed to `Issue248`

**Comment by HHS81** [comment] 2018-02-11 17:55
A  bit weak flashlight, as it doesn't bright up the floor....

**Comment by wlbragg** [comment] 2018-02-11 18:03
OK, I'll take your word for it. I just did some isolating of aircraft on my system and it did clear some things up. I have a really tough time if I use the launcher for developing as it pulls resources from who knows where. Once I isolated it to the command line it sorted it out some.
Thanks!

>A bit weak flashlight, as it doesn't bright up the floor....
<light-radius type="float">13</light-radius>
I think the above is the only adjustment readily available other than color. You can make it a larger radius so it reaches the floor?
 
So I am done here?

**Comment by wlbragg** [comment] 2018-02-11 18:05
P.S.
~~~
Could not find at least one of the following objects for axis animation: knob-inner-axis
Could not find at least one of the following objects for axis animation: Hdg-Knob-axis
Could not find at least one of the following objects for axis animation: OBS-Knob-axis
Could not find at least one of the following objects for axis animation: click-R-axis
Could not find at least one of the following objects for axis animation: click-R-axis
~~~
This does appear to be a "master" issue though and I couldn't track it down.

**Comment by HHS81** [comment] 2018-02-11 18:06
@wlbragg 
I use the launcher, but it doesn't pull from somewhere. 

Say, which FGFS-version are you using?
I had the above error message some time ago with an older dev-version. Not a bug of the c182s, but of FlightGear itself.

**Comment by wlbragg** [comment] 2018-02-11 18:15
>I use the launcher, but it doesn't pull from somewhere.
@HHS81 I think it has to do with multiple version of the same aircraft in two separate locations but both being included in the launcher search path.

For example, I had just switched to an isolated c182s "master" version and the log was still giving me the errors for the white.png not being found. It makes if really difficult to debug with that kind of faulty debug info. As soon as I ran the same isolated c182s "master" version from the command line the errors went away.

**Comment by HHS81** [comment] 2018-02-11 18:19
When I have two seperated folder with different versions of the same aircraft (e.g. FGaddon vs. GitHub-dev) I always get the one on top of the list in the launcher

**Comment by wlbragg** [comment] 2018-02-11 18:49
Your right, I just took another look and I think I started the wrong one in the launcher. I hover over them in the launcher list and look at the path to make sure it is the right one, I must have simply mistaken the path for the one I wanted because it just now worked correctly and I got the correct log results.

**Comment by wlbragg** [comment] 2018-02-11 19:00
@hbeni  and @HHS81 
OK, so where are we at here and what is the workflow?
You decided you are not going to do interior radiance?

If that is correct then I am going to change all the names of the calling effect to flashlight instead of interior_radiance.

Then after I push that, we're done and you want a PR request and you'll take care of merging it into master?

**Comment by HHS81** [comment] 2018-02-11 19:48
@wlbragg 
In the newest PR we added some more objects, like the POH, the annunciator panel....
We should wait until this had been merged, then we can merge it into master and see which objects are missing

**Comment by wlbragg** [comment] 2018-02-11 19:55
@HHS81 
You decided you are not going to do interior radiance?

**Comment by HHS81** [comment] 2018-02-11 19:58
@wlbragg 
I never saw this effect in the c172p, and what Thorsten wrote [here](https://forum.flightgear.org/viewtopic.php?f=47&t=32511&start=45#p315427), is done already by preshading the interior.

**Comment by wlbragg** [comment] 2018-02-11 21:08
This is different from the irradiance map. This is a special effect that when flying in the dark allows the radio (or any equipment you add to the effect) to change the soft glow of light on all the interior surfaces. So if you dim or brighten the radio leds the interior of the cockpit surfaces reflect that subtle light or lack of it. 

Try it in the c172p, go dark and adjust the panel light knob while looking at the armrest or door handle and watch what happens.

**Comment by HHS81** [comment] 2018-02-11 21:11
@wlbragg 
hmmm, never noticed.
Do I need level 5?

**Comment by wlbragg** [comment] 2018-02-11 21:13
By the way, another unrelated issue I don't necessarily want to make a issue for.
~~~<reflection-fresnel-factor type="float"><use>/sim/rendering/fresnel-factor</use></reflection-fresnel-factor>
<reflection-type type="int"><use>/sim/rendering/refl-type</use></reflection-type>
~~~
These two properties are not defined in the set file and thus cause the c182sreflect-uber.eff effect to fail. The exterior of my aircraft was always black without a workaround. I finally tracked it down (took a hour or more). I don't know why others didn't see this but that is what the issue was. They need a definition in the set file.
~~~
<reflection-correction type="float"><use>/sim/rendering/refl_correction</use></reflection-correction>
~~~
This one is defined and works.

**Comment by wlbragg** [comment] 2018-02-11 21:14
@HHS81 
>Do I need level 5?

I don't know for sure, probably?

**Comment by HHS81** [comment] 2018-02-11 21:15
@wlbragg 
o.k. regardingreflection-shader: then I will add a hotfix quite soon. probably a driver issue when I don't see it.

**Comment by hbeni** [comment] 2018-02-11 21:18
I keep an experimental master-merged branch on my local machine where i was abke to merge this in and it seems its all lightened okay.

**Comment by HHS81** [comment] 2018-02-11 21:28
I haven't tried the c172p with the interior radiance effect. If this is good, it would be nice feature (for the C182T we would need a more white color then)

**Comment by wlbragg** [comment] 2018-02-11 21:36
OK, so you want me to just add to this issue , ie: "Add flashlight and radiance effect"?

Then I will start setting up the als-light.xml portion by adding the instruments that affect the light radiance and we can adjust for strength and color.

**Comment by HHS81** [comment] 2018-02-11 21:49
@wlbragg 
It is very subtile, but works below Level 5. And it isn't red as I expected. 
But yes, go on! 👍

**Comment by wlbragg** [comment] 2018-02-14 04:29
OK, I have the initial RA effect in place. I am still adjusting the color and the amount of RA light. Also I still have some switch, dimming and power logic adjustments to make.
I was hoping to get some feedback as to what you all think to this point about the visual?

**Comment by wlbragg** [comment] 2018-02-14 17:16
I'm done as far as I know, PR has been created.

**Closed** 2018-02-14 20:10 UTC
Labels: effects, enhancement
