### ISSUE TITLE
Engine dies when in idle

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#279] opened 2018-07-23 08:58 UTC
> Engine dies when in idle at UT44- should not happen

Yes, the engine dies easily after start currently. It can be mitigated by adjusting throttle a little higher (play with it after engine fired). It can also happen at lower airports.
I dont't know what is causing this. Maybe this is also realistic with a cold engine?

**Comment by HHS81** [comment] 2018-07-23 10:19
Hmm.... I don't know. Maybe it  is this time something I introduced.

**Comment by hbeni** [comment] 2018-07-23 13:51
I have the oiltemp-still-cold friction in mind.
I will check this.

**Comment by hbeni** [comment] 2018-07-23 15:40
Ok, i investigated.
It is not the low oil temperature causing friction, it has something to do with the manfold pressure/throttle.

You need at least 40% throttle at UT44, so the engine gets enough air to combust, otherwise it would quickly starve. After it stabilized a few secs later, one can reduce the throttle to at least 35%, there it starves.
I dont't know if this is realistic but assume yes, as the manfold pressure gets too low (below green arc / <15inHG). Once the engine fires, it sucks some more air (maybe caused by the richer mixture from priming?) but then stabilizes at a lower demand rate.

If the behavior is somewhat correct, what needs adjustment is the autostart code so the throttle is set to a value allowing the engine to survive. Since no other effects are effective (they are disabled shortly) when using autostart, i think this is something in jsbsim - either realistic/woks-as-designed or something with our XMLs.

@HHS81 What do you think?

**Comment by hbeni** [comment] 2018-07-24 09:53
Good luck and let me know if i can assist!

**Comment by HHS81** [comment] 2018-07-29 15:55
@hbeni  O.k, indeed it had been the values.
Nethertheless there is still an issue: with complex engine procedures enabled fuel flow reduces a lot, and with that the power. So the whole numbers aren't matching the POH not anymore with complex engine procedures enabled! 
After a short time the engine sputters, coughs. Black smoke appears and the egine dies. 
That's not realistic as well since the engine should run at full power with high CHT longer than 5-10min without any damage. Propably even longer but then engine wear can be expected.

**Comment by HHS81** [comment] 2018-07-29 16:13
@hbeni I fixed the values in master-branch since it was just a small change

**Comment by hbeni** [comment] 2018-07-29 20:37
@HHS81 Thanks for fixing this!

With complex engine procedures two factors come into play that may explain this.
First, if the engine oil is cold, additional friction will be present because of viscosity, the engine should develop full power once the oil temp is > 75°F. Can you please recheck the friction numbers?
Second; high CHT temps will also lead to friction since the cylinder heads are simulated to be expanding until metal to metal contact.

The engine killed with black smoke is the consequence of too high CHT. When the CHT is too high for too long (currently about two minutes i think) the behaviour you see should appear.
I do not know realistic numbers. what do you propose here?

Both of you issues should not be a problem unless you try to give full power at taxi or while standing on the ground. At takeoff the cooling should be quickly cool the CHT down to reasonable numbers, letting the engine develop full power.


The system is in place and ready to be tunes, but what exactly should be changed and to what numbers?

**Comment by hbeni** [comment] 2018-07-30 15:39
Let me further explain the current implementation:
- engine damaging just boils down to "high internal friction" currently.
- When friction exceeds >25 Horsepowers, this is considered "damaging high"
 the engine survives about one minute in this state currently without damage. If it persists linger than this, the engine will die with the symptoms you described above.
- Friction is caused by:
  - CHT too high (red mark+little buffer)
  - cold oil (but about 10HP in normal conditions)
  - oil too hot (>280°F)
  - oil press too low (>20 PSI)

To simulate this correct, we may need to better differentiate the "what damages engine" states, together with a TBO simulation bringing us long time engine wear. the engine could then very quickly wear down without oil pressure (2 minutes say) and more slowly with high friction values (to mitigate high CHT wear out).
This would give us quick dead engines when oil pressure is lost (failure) and slow starvation when high CHTs lead to high friction.


But again, what exactly is the behaviour you want to see (so i an code up against it)?

**Comment by hbeni** [comment] 2018-07-30 15:40
@HHS81 also, i tried to test current master. Even with complex engine procedures off, i need about 40% Throttle to be able to start the engine.

**Comment by HHS81** [comment] 2018-07-30 18:29
@hbeni 
> also, i tried to test current master. Even with complex engine procedures off, i need about 40% Throttle to be able to start the engine.

Can't reproduce it. With complex engine procedures off the engine starts as it should, runs in idle as well. 

Following things I just observed with complex engine procedures on:
Starting it is more difficult, especially as it is cold at this altitude with Standard ISO weather.
I flooded the engine quite fast, only little prime is needed. But then with flooded engine procedures the engine start's right off. (Some real pilots even uses this procedure for cold weather).
When you get it right (manifold-level-norm = ~ 0.72) engine starts as well. 
Then it needs a whole while until engine is warm and oil temp is >75°F. Until that the engine dies below throttle 40% - that's what you observed. But even with warm engine dies at throttle ~0.0.

As soon I give full power CHT raises above red line and friction-hp increases immediately to 50hp. That's a lot. Usually at this altitude (Standard ISO Weather) you will have about ~154HP static power. But with complex engine procedures you will only get ~100HP. Soon when you deactivate the parking brake and you gained some speed, CHT falls and power raises to value above.

In both cases the automatic let the aircraft start without any problem.

> But again, what exactly is the behaviour you want to see (so i an code up against it)?

Not want I want to see, what we can expect to be realistic. The POH states at p. 4-24: 

> It is important to check full throttle engine operation early in the takeoff roll. [...] If this occurs, you are justified in making a thorough full throttle static runup before another takeoff is attempted. 

Also in the same part leaning according the Maximum Power fuel flow placard in a full throttle static runup is recommended.
So I guess 2 min is much too short time and the immediately raising of friction-hp doesn't seems right to me. Usually most engines should run fine with full static power without any damage with 5-10min as this number is often mentioned in aircraft manuals. Unfortunately the POH doesn't say anything about.

**Comment by hbeni** [comment] 2018-07-31 20:34
Okay, i understand. The solution is to decouple frictiin from damage.
I will get on this soon! Thanks for clarifying :)

**Comment by hbeni** [comment] 2018-08-03 13:52
@HHS81 I have a local branch ready now, just need to tune and test.
It allows us to independently adjust killing causes and their timings.
Currently high CHT leads to smoke in about 4:30 minutes and killed engine after 20 more seconds, so the pilot has a slight chance of recovering from too hot CHT now. Low oil lubrication (too high temps or too low pressure) leads to smoke in 1:30 and killed engine in 2:00.

Friction system is now decoupled and friction also reduced.

**Comment by hbeni** [comment] 2018-08-06 20:53
Turned out, the cylinder head mass and cylinder count where not properly defined in engine.xml.
I adjusted this (however was not able to find real numbers!) to 10KG per cylinder head.

With the current state the engine dies on the ground after about 2:30 due to ripping oil film (oil too hot).
With disabled oil-feature, it dies from high CHT at about 5 minutes, but CHT is way up over 1000°F then.


I think this is much more close to what should happen and maybe already "ok" enough for this simulation:
- full throttle operation on the ground is now possible without any effects to about one minute. That should be plenty time for start up procedures and to adjust for max performance.
- after that the engine looses power slowly over time, but this is not as drastic as before and barely noticeable
- still misuse will lead to permanent engine death after > 2:30 (so full throttle on ground for longer times is still no good idea)

What i still wonder: shouldn't the pistons get squeezed to the point they can barely move anymore at some point >500°F CHT due to expansion forces (that is, 30hp friction seems to low)?
The lycoming manual also says:
![image](https://user-images.githubusercontent.com/13608602/43740281-190e67c2-99cb-11e8-8698-a3c97c199bf7.png)




@HHS81 You can test this yourself in branch https://github.com/HHS81/c182s/tree/Issue279-2 :wink:

If you are fine with the current behavior, just merge.
If you want some adjustments, let me know.
If you want to go with the old (much simpler!) implementation, just merge the commit 0ef5211634e3b29a containing the new engine specs.

**Comment by hbeni** [comment] 2018-08-06 21:22
That said, it would really be an option to just merge https://github.com/HHS81/c182s/commit/0ef5211634e3b29a6b940d511e0742a236661b54 and keep the old, simpler system as it is more easy to tune and still does mainly the same - the main handle was adjusting engine.xml. We can think of lowering the CHT temp based friction to, say 25 or so and give the failure-filter-detector a little more tolerance time, so high cht's are tolerated longer. We also may shift the friction table CHT max-value a little more to the high temps, so the friction-gradient is less steep (so friction build up is slower).

**Comment by HHS81** [comment] 2018-08-06 21:44
@ hbeni the only hinter I found was in the comment Section of following link: https://aviation.stackexchange.com/questions/2561/when-to-reduce-power-on-takeoff-cessna-182-or-similar

It states that FAR 25 and maybe FAR 23 says that a engine must run for 5 min takeoff thrust.  I couldn't find unfortunately

**Comment by HHS81** [comment] 2018-08-06 22:09
I will test soon

**Comment by hbeni** [comment] 2018-08-06 22:35
I interpret the Links text to maintain 5 min takeoff power at takeoff procedure, not with brakes applied. They are discussing "when to reduce power after takeoff was commenced"...

I would leave the values as currently implemented, until we get better data (especially as it should roughly be in the correct ballpark), what do you think?

**Comment by HHS81** [comment] 2018-08-09 16:57
@hbeni 
it isn't really clear, but FAR Part 23 FAR Part 25 doesn't say much about. I have no idea what is realistic.

But: 

> What i still wonder: shouldn't the pistons get squeezed to the point they can barely move anymore at some point >500°F CHT due to expansion forces (that is, 30hp friction seems to low)?

No, as I can remember metal doesn't expands suddenly when temperatures increases. And there must be a large expansion to do so.

**Comment by HHS81** [comment] 2018-08-09 17:11
Hmmm.... Still engine dies at < 40% Throttle at an OAT of 5°C and below oil temp of 75°F. I'm sure that's not right.

**Comment by HHS81** [comment] 2018-08-09 17:41
10kg per cylinder head is a lot. I once saw a documentation about beeing a worker at Daimer in Untertürkheim. The worker hat to lift a cylinderhead for 4 cylinders made of aluminium with 12kg together. 
Lycoming also uses aluminum (acording wiki it is a light metal) so I would guess it is less, about 3kg per cylinder head.

**Comment by hbeni** [comment] 2018-08-10 07:39
But what is causing this?

**Comment by HHS81** [comment] 2018-08-10 17:09
@hbeni  the oil temp friction is just one thing. For those temperatures the friction is too strong. The other thing is that the engine needs to high rpm and too long to get warm. It is simply like that.

**Comment by hbeni** [comment] 2018-08-22 11:52
@HHS81 in branch `Issue279-2`, new commit 913aba5 it seems to be solved.
I adjusted cylinder head mass to 4KG and the low oil temp friction is only applied above 1000 RPM now.

This lets the engine start with 10% throttle and 80% mixture and keeps it running at UT44 @-5°C.
It warmed the Oil to 70°F in about 5:30 at 1200RPM.

The only side effect is, that critical CHT temps are reached faster now.

**Comment by hbeni** [comment] 2018-08-22 11:54
01a596a now lowered the coughing due to low oil temp, "ready for takeoff" state should be a little more early now.

![image](https://user-images.githubusercontent.com/13608602/44461818-aacd3f00-a612-11e8-86e1-110b515df7b7.png)

**Comment by hbeni** [comment] 2018-08-22 11:54
@HHS81 do you think it is ready for merge now, or does it still need adjustment somewhere?

**Comment by hbeni** [comment] 2018-08-26 16:05
I currently test some minor changes regarding oil temp:
- high oil temp now just leads to friction, no more engine death from this cause (high CHT and low oil pressure still remains)
- high oil temp now leads to slightly higher consumption (oil burn)
- CHT heat death is still not rightly timed and also needs compensation because of lower CHT mass from change 913aba5 (i shoot for about 4-5 minutes)

**Comment by hbeni** [comment] 2018-08-27 11:07
Ok, new test results; at UT44 @ -10°C
- Priming and starting worked, engine was stable at 8% throttle setting and did not die (=main issue fixed)
- Warmup period took about 4:30 at 1200RPM with the engine run up test about every 40 secs (pasted image above)
- CHT took about 1:00 to reach red line (500°F)
- After about 2:00 the CHT friction reaches its max@30hp
- After 4:00 smoke appears (3min is the lycoming max!)
- Engine dies at 4:15 and stops at 4:20.

- Failure of oil pump still works (kills after about 1:50)
- Low oil level still leads to engine failure by too oil low press with high oil temps

@HHS81 Looks better now, don't you think?

**Comment by hbeni** [comment] 2018-08-29 19:58
@HHS81 Today conducted a test at EDDM at 140°F/60°C (i have let the CHT rech this temp before conducting tests as jsbsim initializes always at 60°F) and the results were nearly the same, but a little more early as can be expected at hot weather.
- Smoke occured at 3:30
- Engine was stopped at 3:45

I will file PR now, as i think this should be ready for merge.
Feel free to merge once you tested this and are satisfied :)

**Comment by HHS81** [comment] 2018-08-30 21:38
@hbeni Great work!
Thanks a lot! :+1: :+1: 

> now lowered the coughing due to low oil temp, "ready for takeoff" state should be a little more early now.

Damn; I missed that part of the POH.
I think 4min start for smoke seems o.k, since it need some time to generate such smoke

Everything o.k., will be merged, and immediately put into FGAddon!

**Closed** 2018-08-30 21:38 UTC
Labels: bug, procedures, systems
