### ISSUE TITLE
Walker cant't climb ladder anymore

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#213] opened 2017-12-16 11:19 UTC
At least in my installation the walker walks through the ladder....
This makes it "hard" to complete the preflight checklist without loosing immersion.

**Comment by HHS81** [comment] 2017-12-16 11:49
No need to open a New issue. The issue is already known and need to be fixed in the core.

**Closed by HHS81** 2017-12-16 11:49 UTC
Labels: bug, procedures

**Comment by hbeni** [comment] 2017-12-16 20:49
Oh, sorry, i was not aware of this and tought it was an issue with the model.
Do you have any reference for me to read up on it?

**Comment by HHS81** [comment] 2017-12-16 21:42
@hbeni  I noticed the issue [here ](https://github.com/HHS81/c182s/pull/167#commitcomment-24556389).
And [here you can follow the answer on the mailing-list](https://sourceforge.net/p/flightgear/mailman/message/36059076/)
